### ISSUE TITLE
The @CustomLog annotation is not configured; please set lombok.log.custom.declaration in lombok.config.

### ISSUE THREAD

**Issue by neyas** [microsoft/vscode-lombok#103]
1. Create a file named 'lombok.config' in the root of project folder
2. Add line `lombok.log.custom.declaration=com.sap.dpi.v2.lib.commons.logger.ApplicationLogger com.sap.dpi.v2.lib.commons.logger.LoggerStrategy.getLogger(TYPE)` to the above file.
3. Add the annotation @CustomLog to one of the project class file. 
4. VSCode gives error message as `The @CustomLog annotation is not configured; please set lombok.log.custom.declaration in lombok.config.`

**Comment by singlow** [comment]
It appears that `lombok.log.fieldName=mylog` is also not respected. Vscode generates a default `log` field instead of my custom name.

**Comment by singlow** [comment]
I will add that this just started recently for my team and reverting to older versions of the plugin didn't resolve it. So maybe this is caused by other changes in vscode recently?

**Comment by singlow** [comment]
So from the docs it looks like the basic lombok annotation processing is handled in the `Language Support for Java(TM) by Red Hat` plugin now. I reverted that plugin to v1.13.0 and the problem went away. So I assume it is not related to this plugin at all.

**Comment by testforstephen** [comment]
Duplicates with https://github.com/redhat-developer/vscode-java/issues/2887. Since the lombok support is now provided by upstream redhat.java extension, let's use the upstream issue to track the progress.
