### ISSUE TITLE
Lombok extension updates User level setting in Remote Container mode

### ISSUE THREAD

**Issue by navneetkarnani** [microsoft/vscode-lombok#49]
I am using the "Remote Containers" extension to connect to a Docker container where I do my development for a project.

When I install the Lombok extension on the host machine, it updates the "User" settings to have the "javaagent" with the path of the jar from the user home directory.

When I am working inside a "Remote Container" hosted on my local Docker machine, I have the option to install extensions that are relevant to that container. But, at this time, when I install the extension, the "User" setting already has the "javaagent" entry from the host, and hence the Java language server fails to start. The host user directory is not available on the Container. 

The work around is to open the user settings.json file and remove the "javaagent" entry from there. But then, that means I cannot use the extension on my host machine.

When running inside a container, the extension settings should be added to the "Remote" settings instead of the "User" settings.

**Comment by svenefftinge** [comment]
This same issue happens with Gitpod where vs code extensions are installed per repository. I.e. after starting a workspace on a repo that includes Lombok, the user settings will be updated automatically. Starting any Java repo without the lombok extension afterward will break the Java language server.

**Comment by navneetkarnani** [comment]
Here is a reply I got from the VS Code folks. This should help:
https://github.com/microsoft/vscode-remote-release/issues/4230#issuecomment-755371108

**Comment by Zoomink** [comment]
Any progress on this?

**Comment by testforstephen** [comment]
In the latest version 1.1.0, the lombok agent in this extension is removed because RedHat Java extension has built-in lombok support by default. This lombok extension no longer injects lombok agent to 'java.jdt.ls.vmargs'.
