### ISSUE TITLE
Do not use 'java.jdt.ls.vmargs' for attaching the agent

### ISSUE THREAD

**Issue by stefanrybacki** [microsoft/vscode-lombok#75]
'java.jdt.ls.vmargs' will be used in workspace settings across multiple dev machines and setup (remote, containers, local, etc.)
adding the agent there will not be compatible with all those setups as the path to the lombok.jar will be different depending on the setup and OS

**Comment by testforstephen** [comment]
In the latest version 1.1.0, the lombok agent in this extension is not removed because RedHat Java extension has built-in lombok support by default. This lombok extension no longer injects lombok agent to 'java.jdt.ls.vmargs'.

**Comment by stefanrybacki** [comment]
sweet
