### ISSUE TITLE
Release new version with updated identifier

### ISSUE THREAD

**Issue by blizzy78** [microsoft/vscode-lombok#79]
The recent change from plugin ID `GabrielBB.vscode-lombok` to `vscjava.vscode-lombok` seems to produce problems.

When trying to install the extension in a dev container, I can see after unpacking `~/.vscode-server/extensionsCache/vscjava.vscode-lombok-1.0.1` that the identifier is still the old one:

~~~xml
<Identity Language="en-US" Id="vscode-lombok" Version="1.0.1" Publisher="GabrielBB"/>
~~~

Additionally, after installing the plugin, it does not seem to be activated by the remote extension host, which renders it unusable.

The plugin was installed in the dev container under `~/.vscode-server/extensions/vscjava.vscode-lombok-1.0.1/`, but again, the identifier is the old one. Changing the identifier manually in `~/.vscode-server/extensions/vscjava.vscode-lombok-1.0.1/.vsixmanifest` and restarting did not help.

**Comment by blizzy78** [comment]
Doing the following

- rename `~/.vscode-server/extensions/vscjava.vscode-lombok-1.0.1/` to `gabrielbb.vscode-lombok-1.0.1/`
- remove entry for `gabrielbb.vscode-lombok` from `~/.vscode-server/extensions/.obsolete`
- rename `~/.vscode-server/extensions/vscjava.vscode-lombok-1.0.1` to `gabrielbb.vscode-lombok-1.0.1`
- restart

helped, and the remote extension host is now starting the extension again.

But it still does not resolve Lombok annotations, despite having added `-javaagent:\"/home/vscode/.vscode-server/extensions/gabrielbb.vscode-lombok-1.0.1/server/lombok.jar\"` to the `java.jdt.ls.vmargs` setting for the dev container remote.

**Comment by blizzy78** [comment]
I have updated my Maven project from an older Lombok version (1.16.x) to the latest version. After accepting a prompt to reload the VS Code window, the issue resolved itself, and Lombok annotations are being resolved again.

I still believe the extension should be released with a new version and correct extension ID.

**Comment by pinkli** [comment]
I've tred to change every occurence of `gabrielbb` into `vscjava`, but it doesn't work. 
The `java.jdt.ls.vmargs` setting seems to be valid.

**Comment by nedlosster** [comment]
After change to version with updated identifier i have that error:

  message: 'Failed to find Premain-Class manifest attribute in /home/app/.m2/repository/org/projectlombok/lombok-mapstruct-binding/0.2.0/lombok-mapstruct-binding-0.2.0.jar\n',

**Comment by blizzy78** [comment]
> After change to version with updated identifier

There doesn't seem to be a new release yet, or am I missing something?

**Comment by blizzy78** [comment]
Nevermind. The `redhat.java` extension now supports Lombok natively. `GabrielBB.vscode-lombok` and `vscjava.vscode-lombok` can simply be uninstalled.
